name: First Workflows
on:
  push:
    jobs:
    build:
    runs-on: ubuntu-latest
    steps:
    -name: checkout code
    user: actions/checkout@v4
    -name: print build started
    run: echo"build started"
