name: First Workflows

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: print build started
        run: echo "build started"
